// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/bxcodec/go-clean-arch/domain"
	mock "github.com/stretchr/testify/mock"
)

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type BMIRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id


// Store provides a mock function with given fields: ctx, a
func (_m *BMIRepository) Store(ctx context.Context, a *domain.BMI) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BMI) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// The first argument is typically a *testing.T value.
func NewBMIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BMIRepository {
	mock := &BMIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
