// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (

	mock "github.com/stretchr/testify/mock"
)

// ArticleService is an autogenerated mock type for the ArticleService type
type BMIService struct {
	mock.Mock
}

// NewArticleService creates a new instance of ArticleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBMIService(t interface {
	mock.TestingT
	Cleanup(func())
}) * BMIService{
	mock := &BMIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
